In [18]:
import numpy as np
import sys
sys.path.append("../code/")
from dataloader import APPLIANCE_ORDER, get_train_test


In [178]:
stf_pred = {}
stf_pred[1] = np.load("../code/baseline/result/stf-pred-12.npy").item()[1]
stf_pred[3] = np.load("../code/baseline/result/stf-pred-34.npy").item()[3]

In [179]:
mtf_pred = {}
mtf_pred[1] = np.load("../code/baseline/result/mtf-pred-12.npy").item()[1]
mtf_pred[3] = np.load("../code/baseline/result/mtf-pred-34.npy").item()[3]

In [180]:
active_threshold = {'hvac':230, 'fridge':20, 'dr':250, 'dw':55, 'mw':10}

In [181]:
num_homes = {0:14, 1:14, 2:14, 3:13, 4:13}

In [182]:
# calculate gt
test_gt = {}
valid_gt = {}
for fold_num in range(5):
    test_gt[fold_num] = {}
    valid_gt[fold_num] = {}
    train, test = get_train_test(1, 5, fold_num)
    valid = train[int(0.8*len(train)):].copy()
    for idx, appliance in enumerate(APPLIANCE_ORDER[1:-1]):
        test_gt[fold_num][appliance] = test[:, idx+1]
        valid_gt[fold_num][appliance] = valid[:, idx+1]

In [183]:
active = {}
for dataset in [1, 3]:
    active[dataset] = {}
    for fold_num in range(5):
        active[dataset][fold_num] = {}
        for idx, appliance in enumerate(APPLIANCE_ORDER[1:-1]):
            active[dataset][fold_num][appliance] = (test_gt[fold_num][appliance] > active_threshold[appliance])*1

In [184]:
TP = {}
TP_FP = {}
TP_FN = {}
for dataset in [1, 3]:
    TP[dataset] = {}
    TP_FP[dataset] = {}
    TP_FN[dataset] = {}
    for idx, appliance in enumerate(APPLIANCE_ORDER[1:-1]):
        TP[dataset][appliance] = 0
        TP_FP[dataset][appliance] = 0
        TP_FN[dataset][appliance] = 0
        for fold_num in range(5):
            test_active = (stf_pred[dataset][fold_num][:, idx] > active_threshold[appliance])*1
            TP[dataset][appliance] += np.multiply(test_active, active[dataset][fold_num][appliance]).sum()
            TP_FP[dataset][appliance] += test_active.sum()
            TP_FN[dataset][appliance] += active[dataset][fold_num][appliance].sum()

In [185]:
for dataset in [1, 3]:
    for idx, appliance in enumerate(APPLIANCE_ORDER[1:-1]):
        pr = TP[dataset][appliance]/TP_FP[dataset][appliance]
        recall = TP[dataset][appliance]/TP_FN[dataset][appliance]
        
        print(appliance, "Precision: ", pr, "Recall: ", recall)


hvac Precision:  0.811093983185 Recall:  0.977586308995
fridge Precision:  0.978629785109 Recall:  0.920857835046
dr Precision:  0.125 Recall:  0.05203969129
dw Precision:  0.0887822435513 Recall:  0.0397689103856
mw Precision:  0.174036595509 Recall:  0.484632086852
hvac Precision:  0.796154888292 Recall:  0.956993545331
fridge Precision:  0.977819653745 Recall:  0.96098003122
dr Precision:  0.113482056256 Recall:  0.0386990077178
dw Precision:  0.0626020685901 Recall:  0.0463522773075
mw Precision:  0.15893247776 Recall:  0.262919179735


In [186]:
TP = {}
TP_FP = {}
TP_FN = {}
for dataset in [1, 3]:
    TP[dataset] = {}
    TP_FP[dataset] = {}
    TP_FN[dataset] = {}
    for idx, appliance in enumerate(APPLIANCE_ORDER[1:-1]):
        TP[dataset][appliance] = 0
        TP_FP[dataset][appliance] = 0
        TP_FN[dataset][appliance] = 0
        for fold_num in range(5):
            test_active = (mtf_pred[dataset][fold_num][:, idx] > active_threshold[appliance])*1
            TP[dataset][appliance] += np.multiply(test_active, active[dataset][fold_num][appliance]).sum()
            TP_FP[dataset][appliance] += test_active.sum()
            TP_FN[dataset][appliance] += active[dataset][fold_num][appliance].sum()

In [187]:
for dataset in [1, 3]:
    for idx, appliance in enumerate(APPLIANCE_ORDER[1:-1]):
        pr = TP[dataset][appliance]/TP_FP[dataset][appliance]
        recall = TP[dataset][appliance]/TP_FN[dataset][appliance]
        
        print(appliance, "Precision: ", pr, "Recall: ", recall)


hvac Precision:  0.816622527261 Recall:  0.972323384852
fridge Precision:  0.978581370906 Recall:  0.96372161205
dr Precision:  0.125177003682 Recall:  0.0487320837927
dw Precision:  0.0813429472735 Recall:  0.0485019481392
mw Precision:  0.20485015241 Recall:  0.366417370326
hvac Precision:  0.795939687083 Recall:  0.975676555931
fridge Precision:  0.978608407768 Recall:  0.985699019185
dr Precision:  0.106988783434 Recall:  0.0410143329658
dw Precision:  0.0734101579172 Recall:  0.0693268843208
mw Precision:  0.212929915639 Recall:  0.379975874548


In [188]:
sc_pred = np.load("../code/baseline/result/sc-non-disc-pred.npy").item()

In [189]:
TP = {}
TP_FP = {}
TP_FN = {}
for dataset in [1, 3]:
    TP[dataset] = {}
    TP_FP[dataset] = {}
    TP_FN[dataset] = {}
    for idx, appliance in enumerate(APPLIANCE_ORDER[1:-1]):
        TP[dataset][appliance] = 0
        TP_FP[dataset][appliance] = 0
        TP_FN[dataset][appliance] = 0
        for fold_num in range(5):
            test_active = (sc_pred[dataset][fold_num][:, idx] > active_threshold[appliance])*1
            TP[dataset][appliance] += np.multiply(test_active, active[dataset][fold_num][appliance]).sum()
            TP_FP[dataset][appliance] += test_active.sum()
            TP_FN[dataset][appliance] += active[dataset][fold_num][appliance].sum()

In [190]:
for dataset in [1, 3]:
    for idx, appliance in enumerate(APPLIANCE_ORDER[1:-1]):
        pr = TP[dataset][appliance]/TP_FP[dataset][appliance]
        recall = TP[dataset][appliance]/TP_FN[dataset][appliance]
        
        print(appliance, "Precision: ", pr, "Recall: ", recall)


hvac Precision:  1.0 Recall:  0.924735003257
fridge Precision:  0.983653614 Recall:  0.615462515876
dr Precision:  0.179126572909 Recall:  0.0266813671444
dw Precision:  0.0703951506834 Recall:  0.16539029961
mw Precision:  0.1330680745 Recall:  0.414716525935
hvac Precision:  1.0 Recall:  0.955786995914
fridge Precision:  0.978929010105 Recall:  0.807110205954
dr Precision:  0.136469221835 Recall:  0.15545755237
dw Precision:  0.0717382110383 Recall:  0.364637914819
mw Precision:  0.126826346266 Recall:  0.704897466828


In [191]:
dsc_pred = np.load("../code/baseline/result/DSC-pred.npy").item()

In [192]:
TP = {}
TP_FP = {}
TP_FN = {}
for dataset in [1, 3]:
    TP[dataset] = {}
    TP_FP[dataset] = {}
    TP_FN[dataset] = {}
    for idx, appliance in enumerate(APPLIANCE_ORDER[1:-1]):
        TP[dataset][appliance] = 0
        TP_FP[dataset][appliance] = 0
        TP_FN[dataset][appliance] = 0
        for fold_num in range(5):
            test_active = (dsc_pred[dataset][fold_num][:, idx] > active_threshold[appliance])*1
            TP[dataset][appliance] += np.multiply(test_active, active[dataset][fold_num][appliance]).sum()
            TP_FP[dataset][appliance] += test_active.sum()
            TP_FN[dataset][appliance] += active[dataset][fold_num][appliance].sum()

In [193]:
for dataset in [1, 3]:
    for idx, appliance in enumerate(APPLIANCE_ORDER[1:-1]):
        pr = TP[dataset][appliance]/TP_FP[dataset][appliance]
        recall = TP[dataset][appliance]/TP_FN[dataset][appliance]
        
        print(appliance, "Precision: ", pr, "Recall: ", recall)


hvac Precision:  1.0 Recall:  0.979414638479
fridge Precision:  0.984273170267 Recall:  0.462224932719
dr Precision:  0.14131501472 Recall:  0.0158765159868
dw Precision:  0.0785828449654 Recall:  0.0396345559586
mw Precision:  0.176894833464 Recall:  0.195271411339
hvac Precision:  1.0 Recall:  0.981139337952
fridge Precision:  0.98356771308 Recall:  0.392499258654
dr Precision:  0.12187088274 Recall:  0.0407938257993
dw Precision:  0.0633285797285 Recall:  0.161090957947
mw Precision:  0.171051089759 Recall:  0.281737032569


In [232]:
cnn_ind_params = {}
cnn_ind_params[1] = np.load("../code/baseline/result/cnn-individual-new-param-1.npy").item()
cnn_ind_params[3] = np.load("../code/baseline/result/cnn-individual-new-param-3.npy").item()

In [233]:
cnn_ind_pred = {}
for dataset in [1, 3]:
    cnn_ind_pred[dataset] = {}
    for fold_num in range(5):
        cnn_ind_pred[dataset][fold_num] = {}
        iters = cnn_ind_params[dataset][fold_num]['iters']
        lr = cnn_ind_params[dataset][fold_num]['lr']
        for appliance in APPLIANCE_ORDER[1:-1]:
            directory = "../code/baseline/cnn-tree/{}/{}/{}/200000/0.0/".format(dataset, fold_num, lr)
            filename = "test-pred-[\'{}\'].npy".format(appliance)
            cnn_ind_pred[dataset][fold_num][appliance] = np.load(directory+filename).item()[iters][0].reshape(-1, 112, 24)

In [234]:
TP = {}
TP_FP = {}
TP_FN = {}
for dataset in [1, 3]:
    TP[dataset] = {}
    TP_FP[dataset] = {}
    TP_FN[dataset] = {}
    for idx, appliance in enumerate(APPLIANCE_ORDER[1:-1]):
        TP[dataset][appliance] = 0
        TP_FP[dataset][appliance] = 0
        TP_FN[dataset][appliance] = 0
        for fold_num in range(5):
            test_active = (cnn_ind_pred[dataset][fold_num][appliance] > active_threshold[appliance])*1
            TP[dataset][appliance] += np.multiply(test_active, active[dataset][fold_num][appliance]).sum()
            TP_FP[dataset][appliance] += test_active.sum()
            TP_FN[dataset][appliance] += active[dataset][fold_num][appliance].sum()

In [238]:
for dataset in [1, 3]:
    for idx, appliance in enumerate(APPLIANCE_ORDER[1:-1]):
        pr = TP[dataset][appliance]/TP_FP[dataset][appliance]
        recall = TP[dataset][appliance]/TP_FN[dataset][appliance]
        
        print(recall)


0.974499615089
0.994393746958
0.474751929438
0.000671772134892
0.00279855247286
0.959132764849
0.995484784226
0.094046306505
0.000671772134892
0.0086369119421


In [239]:
cnn_tree_params = {}
cnn_tree_params[1] = np.load("../code/baseline/result/cnn-tree-new-param-1.npy").item()
cnn_tree_params[3] = np.load("../code/baseline/result/cnn-tree-new-param-3.npy").item()

In [240]:
# get prediction for cnn tree
cnn_tree_pred = {}
for dataset in [1, 3]:
    cnn_tree_pred[dataset] = {}
    for fold_num in range(5):
        cnn_tree_pred[dataset][fold_num] = {}

        lr = cnn_tree_params[dataset][fold_num]['lr']
        iters = cnn_tree_params[dataset][fold_num]['iters']
        order = cnn_tree_params[dataset][fold_num]['order']

        o = "\', \'".join(str(x) for x in order)
        directory = "../code/baseline/cnn-tree/{}/{}/{}/20000/0.0/".format(dataset, fold_num,lr)
        filename = "test-pred-[\'{}\'].npy".format(o)

        full_path = directory + filename
        cnn_pred = np.asarray(np.load(full_path).item()[iters])

        for idx, appliance in enumerate(order):
            cnn_tree_pred[dataset][fold_num][appliance] = cnn_pred[idx].reshape(-1, 112,24)
    

In [250]:
for dataset in [1,3]:
    for idx, appliance in enumerate(order):
        error = 0
        for fold_num in range(5):
        
            abs_error = np.abs(cnn_ind_pred[dataset][fold_num][appliance] - test_gt[fold_num][appliance])
            error += abs_error.mean()*num_homes[fold_num]
        print(dataset, appliance, error/68)

1 dw 15.5555902935
1 mw 8.61542132821
1 fridge 31.6193608317
1 hvac 163.013847982
1 dr 54.1200015616
3 dw 15.5727870813
3 mw 8.5610754486
3 fridge 33.0850743272
3 hvac 314.495194827
3 dr 70.198766109


In [242]:
TP = {}
TP_FP = {}
TP_FN = {}
for dataset in [1, 3]:
    TP[dataset] = {}
    TP_FP[dataset] = {}
    TP_FN[dataset] = {}
    for idx, appliance in enumerate(APPLIANCE_ORDER[1:-1]):
        TP[dataset][appliance] = 0
        TP_FP[dataset][appliance] = 0
        TP_FN[dataset][appliance] = 0
        for fold_num in range(5):
            test_active = (cnn_tree_pred[dataset][fold_num][appliance] > active_threshold[appliance])*1
            TP[dataset][appliance] += np.multiply(test_active, active[dataset][fold_num][appliance]).sum()
            TP_FP[dataset][appliance] += test_active.sum()
            TP_FN[dataset][appliance] += active[dataset][fold_num][appliance].sum()

In [244]:
for dataset in [1, 3]:
    for idx, appliance in enumerate(APPLIANCE_ORDER[1:-1]):
        pr = TP[dataset][appliance]/TP_FP[dataset][appliance]
        recall = TP[dataset][appliance]/TP_FN[dataset][appliance]
        
        print(recall)


0.972190146266
0.970346166543
0.497574421169
0.00174660755072
0.0198311218335
0.955246639427
0.989162363131
0.223594266814
0.000403063280935
0.024656212304


In [202]:
num_folds=5
def mean_predictions(dataset):
    out = []
    for cur_fold in range(5):
        train, test = get_train_test(dataset, num_folds=num_folds, fold_num=cur_fold)
        pred = np.zeros_like(test[:, 1:, :, :])
#         print(pred.shape)
        
        for appliance in range(test.shape[1]-1):
            for day in range(test.shape[2]):
                pred[:, appliance, day, :] = train[:, appliance+1, day, :].mean(axis=0)
#         print(pred[0, 1, 0, 20])
        out.append(pred)
#     return np.concatenate(out)
    return out


In [203]:
tensor = np.load('../2015-5appliances-true-agg.npy')
# tensor = np.load('../2015-5appliances.numpy.npy')
from sklearn.metrics import mean_absolute_error

dataset = 1
mean_pred = {}
for dataset in [1, 3]:

    gt = tensor[:, 1:, :, :]
    mean_pred[dataset] = mean_predictions(dataset)
# Clamping prediction to aggregate
# pred = np.minimum(pred, tensor[:, 0:1, :,:])

In [204]:
TP = {}
TP_FP = {}
TP_FN = {}
for dataset in [1, 3]:
    TP[dataset] = {}
    TP_FP[dataset] = {}
    TP_FN[dataset] = {}
    for idx, appliance in enumerate(APPLIANCE_ORDER[1:-1]):
        TP[dataset][appliance] = 0
        TP_FP[dataset][appliance] = 0
        TP_FN[dataset][appliance] = 0
        for fold_num in range(5):
            test_active = (mean_pred[dataset][fold_num][:, idx] > active_threshold[appliance])*1
            TP[dataset][appliance] += np.multiply(test_active, active[dataset][fold_num][appliance]).sum()
            TP_FP[dataset][appliance] += test_active.sum()
            TP_FN[dataset][appliance] += active[dataset][fold_num][appliance].sum()

In [205]:
for dataset in [1, 3]:
    for idx, appliance in enumerate(APPLIANCE_ORDER[1:-1]):
        pr = TP[dataset][appliance]/TP_FP[dataset][appliance]
        recall = TP[dataset][appliance]/TP_FN[dataset][appliance]
        
        print(appliance, "Precision: ", pr, "Recall: ", recall)


hvac Precision:  0.753081105573 Recall:  0.984218629715
fridge Precision:  0.977815344888 Recall:  1.0
dr Precision:  0.10296474359 Recall:  0.0283351708931
dw Precision:  0.0756002595717 Recall:  0.031304581486
mw Precision:  0.170584519218 Recall:  0.495102533172
hvac Precision:  0.753081105573 Recall:  0.984218629715
fridge Precision:  0.977815344888 Recall:  1.0
dr Precision:  0.10296474359 Recall:  0.0283351708931
dw Precision:  0.0756002595717 Recall:  0.031304581486
mw Precision:  0.170584519218 Recall:  0.495102533172


In [ ]:
# error of active parts

In [206]:
abs_error = np.abs(stf_pred[dataset][fold_num][:, idx]-test_gt[fold_num][appliance])

In [207]:
np.abs(stf_pred[dataset][fold_num][:, idx]-test_gt[fold_num][appliance]).max()

980.56664810992038

In [246]:
for dataset in [1, 3]:
    print("Dataset ", dataset)
    for idx, appliance in enumerate(APPLIANCE_ORDER[1:-1]):
        active_error = []
        inactive_error = []
        print(appliance)
        for fold_num in range(5):
            abs_error = np.abs(cnn_ind_pred[dataset][fold_num][appliance]-test_gt[fold_num][appliance])
            active_error.append(abs_error[active[dataset][fold_num][appliance] == 1])
            inactive_error.append(abs_error[active[dataset][fold_num][appliance] == 0])
        print("active error", np.hstack(active_error).mean())
        print("inactive error", np.hstack(inactive_error).mean())


Dataset  1
hvac
active error 176.441944054
inactive error 124.973207421
fridge
active error 30.7861995415
inactive error 68.3419463388
dr
active error 769.562772877
inactive error 16.7651197684
dw
active error 369.554248076
inactive error 0.528802435118
mw
active error 56.1540663632
inactive error 2.53591683695
Dataset  3
hvac
active error 341.618561301
inactive error 237.657031824
fridge
active error 32.173882115
inactive error 73.2469665347
dr
active error 1220.60552826
inactive error 10.1334326717
dw
active error 369.344266325
inactive error 0.55564265981
mw
active error 55.9347822511
inactive error 2.50266416949


In [173]:
active_error

[array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.])]