In [1]:
import numpy as np

In [3]:
dataid = np.load("./homeid_10_hourly.npy")
validid = np.load("./valid_homes_index.npy")

In [4]:
dataid.shape
validid.shape

(68,)

In [5]:
valid_dataid = dataid[validid]

In [6]:
# tensor = np.load('../2015-5appliances-true-agg.npy')
from sklearn.cluster import KMeans
ag_tensor = np.load('../2015-5appliances.numpy.npy')
true_tensor = np.load("../2015-5appliances-true-agg.npy")
from sklearn.metrics import mean_absolute_error

ag_agg = ag_tensor[:, 0, :, :]
true_agg = true_tensor[:, 0, :, :]
residual_agg = true_agg - ag_agg

residual_agg = residual_agg.reshape(68, -1)

kmeans = KMeans(n_clusters=3, random_state=0).fit(residual_agg)
kmeans.labels_

array([1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 2,
       0, 1, 1, 0, 1, 0, 2, 1, 1, 1, 1, 0, 1, 1, 0, 1, 2, 1, 1, 1, 1, 0, 2,
       2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 0, 1], dtype=int32)

In [7]:
cluster = {}
for i in range(3):
    cluster[i] = [x for x in range(68) if kmeans.labels_[x] == i]

In [15]:
cluster[2]

[2, 22, 29, 39, 45, 46, 51, 60]

In [8]:
for i in range(3):
    print(valid_dataid[cluster[i]])

[2814 7940 7951 2094 7863 3367 4373 8156 7117 4946 5568 5809]
[ 114  661 2575 2859 3456 3482 5403 6836 6990 7536 8236 9134 8188 2156
 4220   93  871 1169 1415 3723 5395 5921 7627 7850 9982 4514 8956 9278
 4874 7641 8292 3036 9701  434 7901 6101 8565 6063  781 2532 5317  101
 1310 3273 9912 3413 2361  668]
[2018 9737 4526 9248 4957 2242 1507 3916]


In [23]:
for i in range(3):
    print(valid_dataid[cluster[i]])

[2814 7940 7951 2094 7863 3367 4373 8156 7117 4946 5568 5809]
[ 114  661 2575 2859 3456 3482 5403 6836 6990 7536 8236 9134 8188 2156 4220
   93  871 1169 1415 3723 5395 5921 7627 7850 9982 4514 8956 9278 4874 7641
 8292 3036 9701  434 7901 6101 8565 6063  781 2532 5317  101 1310 3273 9912
 3413 2361  668]
[2018 9737 4526 9248 4957 2242 1507 3916]


In [25]:
residual_agg[51]

array([ 2175.2332896 ,  2084.51665652,  2128.26675415, ...,  2338.13337505,
        2084.74982806,  1199.8667272 ])

In [26]:
residual_agg[cluster[2][0]]

array([ 1698.98337555,  1382.63344574,  1401.11658478, ...,  2381.24990082,
        1695.33324432,  1585.33319855])